/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../../module/components/recaptcha/recaptcha.component';
const styles_TeleportReCaptchaComponent:any[] = ([] as any[]);
export const RenderType_TeleportReCaptchaComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_TeleportReCaptchaComponent,data:{}});
export function View_TeleportReCaptchaComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[i0.ɵqud(402653184,1,{renderDiv:0}),(_l()(),i0.ɵeld(0,[[1,0],['renderDiv',
      1]],(null as any),0,'div',[['class','g-recaptcha']],(null as any),(null as any),
      (null as any),(null as any),(null as any)))],(null as any),(null as any));
}
export function View_TeleportReCaptchaComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'teleport-sp-recaptcha',
      ([] as any[]),(null as any),(null as any),(null as any),View_TeleportReCaptchaComponent_0,
      RenderType_TeleportReCaptchaComponent)),i0.ɵdid(4374528,(null as any),0,i1.TeleportReCaptchaComponent,
      ([] as any[]),(null as any),(null as any))],(null as any),(null as any));
}
export const TeleportReCaptchaComponentNgFactory:i0.ComponentFactory<i1.TeleportReCaptchaComponent> = i0.ɵccf('teleport-sp-recaptcha',
    i1.TeleportReCaptchaComponent,View_TeleportReCaptchaComponent_Host_0,{sitekey:'sitekey',
        theme:'theme',onReset:'onReset'},{callback:'callback',expiredCallback:'expiredCallback'},
    ([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvcGF0cmlja21hcnRpbi9Eb2N1bWVudHMvU2hvdXRQb2ludFByb2plY3RzL1RlbGVQb3J0L3RlbGVwb3J0LWFwcC1tb2R1bGVzL3RlbGVwb3J0LW1vZHVsZS1kZXYtcG9ydGFsL21vZHVsZS9jb21wb25lbnRzL3JlY2FwdGNoYS9yZWNhcHRjaGEuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL2hvbWUvcGF0cmlja21hcnRpbi9Eb2N1bWVudHMvU2hvdXRQb2ludFByb2plY3RzL1RlbGVQb3J0L3RlbGVwb3J0LWFwcC1tb2R1bGVzL3RlbGVwb3J0LW1vZHVsZS1kZXYtcG9ydGFsL21vZHVsZS9jb21wb25lbnRzL3JlY2FwdGNoYS9yZWNhcHRjaGEuY29tcG9uZW50LnRzIiwibmc6Ly8vaG9tZS9wYXRyaWNrbWFydGluL0RvY3VtZW50cy9TaG91dFBvaW50UHJvamVjdHMvVGVsZVBvcnQvdGVsZXBvcnQtYXBwLW1vZHVsZXMvdGVsZXBvcnQtbW9kdWxlLWRldi1wb3J0YWwvbW9kdWxlL2NvbXBvbmVudHMvcmVjYXB0Y2hhL3JlY2FwdGNoYS5jb21wb25lbnQudHMuVGVsZXBvcnRSZUNhcHRjaGFDb21wb25lbnQuaHRtbCIsIm5nOi8vL2hvbWUvcGF0cmlja21hcnRpbi9Eb2N1bWVudHMvU2hvdXRQb2ludFByb2plY3RzL1RlbGVQb3J0L3RlbGVwb3J0LWFwcC1tb2R1bGVzL3RlbGVwb3J0LW1vZHVsZS1kZXYtcG9ydGFsL21vZHVsZS9jb21wb25lbnRzL3JlY2FwdGNoYS9yZWNhcHRjaGEuY29tcG9uZW50LnRzLlRlbGVwb3J0UmVDYXB0Y2hhQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGRpdiAjcmVuZGVyRGl2IGNsYXNzPVwiZy1yZWNhcHRjaGFcIj48L2Rpdj4iLCI8dGVsZXBvcnQtc3AtcmVjYXB0Y2hhPjwvdGVsZXBvcnQtc3AtcmVjYXB0Y2hhPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7O3VEQ0FBO01BQUE7TUFBQTs7O29CQ0FBO01BQUE7MkNBQUEsVUFBQTtNQUFBOzs7OzsifQ==
