/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../module/services/services.module';
import * as i2 from '../../../module/services/account.credentials.service';
import * as i3 from '@angular/http';
import * as i4 from '@ngrx/store';
import * as i5 from '../../../module/services/alerts.service';
import * as i6 from '../../../module/services/message.service';
import * as i7 from '@angular/platform-browser';
import * as i8 from '../../../module/services/billing.service';
import * as i9 from '../../../module/services/integrations.aws.service';
import * as i10 from '../../../module/services/integrations.watson.service';
import * as i11 from '../../../module/services/logs.service';
import * as i12 from '../../../module/services/modal.service';
import * as i13 from '../../../module/services/perms-guard.service';
import * as i14 from '@angular/router';
import * as i15 from '../../../module/services/top-up.service';
import * as i16 from '../../../module/services/usage.service';
import * as i17 from '../../../module/services/user.service';
export const DevPortalServicesModuleNgFactory:i0.NgModuleFactory<i1.DevPortalServicesModule> = i0.ɵcmf(i1.DevPortalServicesModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,
          i2.AccountCredentialsService,i2.AccountCredentialsService,[i3.Http,i4.Store]),
          i0.ɵmpd(4608,i5.AlertsService,i5.AlertsService,[i3.Http,i4.Store]),i0.ɵmpd(4608,
              i6.MessageService,i6.MessageService,[i7.DOCUMENT,i4.Store,i4.ReducerManagerDispatcher]),
          i0.ɵmpd(4608,i8.BillingService,i8.BillingService,[i3.Http,i6.MessageService,
              i4.Store]),i0.ɵmpd(4608,i9.IntegrationsAWSService,i9.IntegrationsAWSService,
              [i3.Http,i4.Store]),i0.ɵmpd(4608,i10.IntegrationsWatsonService,i10.IntegrationsWatsonService,
              [i3.Http,i4.Store]),i0.ɵmpd(4608,i11.LogsService,i11.LogsService,[i3.Http,
              i4.Store]),i0.ɵmpd(4608,i12.ModalService,i12.ModalService,[i7.DOCUMENT]),
          i0.ɵmpd(4608,i13.PermsGuardCanActivate,i13.PermsGuardCanActivate,[i14.Router,
              i4.Store]),i0.ɵmpd(4608,i15.TopUpService,i15.TopUpService,[i3.Http,i4.Store]),
          i0.ɵmpd(4608,i16.UsageService,i16.UsageService,[i3.Http,i4.Store]),i0.ɵmpd(4608,
              i17.UserService,i17.UserService,[i3.Http,i4.Store]),i0.ɵmpd(512,i1.DevPortalServicesModule,
              i1.DevPortalServicesModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvcGF0cmlja21hcnRpbi9Eb2N1bWVudHMvU2hvdXRQb2ludFByb2plY3RzL1RlbGVQb3J0L3RlbGVwb3J0LWFwcC1tb2R1bGVzL3RlbGVwb3J0LW1vZHVsZS1kZXYtcG9ydGFsL21vZHVsZS9zZXJ2aWNlcy9zZXJ2aWNlcy5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vaG9tZS9wYXRyaWNrbWFydGluL0RvY3VtZW50cy9TaG91dFBvaW50UHJvamVjdHMvVGVsZVBvcnQvdGVsZXBvcnQtYXBwLW1vZHVsZXMvdGVsZXBvcnQtbW9kdWxlLWRldi1wb3J0YWwvbW9kdWxlL3NlcnZpY2VzL3NlcnZpY2VzLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
